ALTER TABLE products
  ADD COLUMN IF NOT EXISTS brand VARCHAR(180) NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS unit VARCHAR(30) NOT NULL DEFAULT 'adet',
  ADD COLUMN IF NOT EXISTS shelf_code VARCHAR(80) NOT NULL DEFAULT '';
